Editable table
orogenic/mabcs pull request #37
Opened 2020-10-31 23:22 UTC by jonathan-mejia-deluna

I clearly am not using best practices given this many commits, but the amount data cell is editable and I'll work on making sure the  balances are correct given an amount edit

2020-11-01 04:11 UTC, orogenic reviewed
The functionality appears incomplete so there isn't much for me to comment on yet. Once you've got a subset of the program functionality working, remember thinking about how to extend it "dimensionally", and think of how to reduce your workload by not creating redundancy (keeping your code "DRY" or "orthogonal"). Your event listener functions are looking kind of similar, and you'll also probably want to reuse your XHR code somehow.

2020-11-01 04:11 UTC, orogenic commented on static/transaction.js
> +        var content = td.textContent.slice(1);      // omits the '$'
small naming nitpick. "content" is not a very semantically specific name, and it also doesn't exactly match the underlying semantically generic name. go either direction, use a more semantically specific name like "amountText", or match exactly the underlying semantically generic name, and call it "textContent".

2020-11-01 04:11 UTC, orogenic commented on static/transaction.js
> +        button.innerHTML = "Change";
if you're setting a value which is just plain text, and not HTML text, no need to use innerHTML. use textContent property instead.

2020-11-01 04:11 UTC, orogenic commented on static/transaction.js
> +            FD.append("transactionID", id); // appends transaction id to form data for db query
another redundant comment.

2020-11-01 04:11 UTC, orogenic commented on templates/transaction.html
> +        <tr id={{ transaction.id }}>
this probably doesn't cause any issues, but i may suggest using a custom data attribute, as these transaction IDs are really in a separate class from HTML element IDs. https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-*

2020-11-03 23:50 UTC, jonathan-mejia-deluna commented on templates/transaction.html
> +        <tr id={{ transaction.id }}>
I'm not sure what you mean by custom data attribute. The link you posted gives me a 404

2020-11-03 23:54 UTC, jonathan-mejia-deluna commented on templates/transaction.html
> +        <tr id={{ transaction.id }}>
I think I understand now

2020-11-03 23:56 UTC, orogenic commented on templates/transaction.html
> +        <tr id={{ transaction.id }}>
the asterisk at the end is part of the URL, a victim of github formatting

2020-11-04 00:31 UTC, jonathan-mejia-deluna commented
Review this when you can. I don't see any other changes needed.

2020-11-04 02:31 UTC, orogenic reviewed
small comments. have not tested. will test tmmrw.

2020-11-04 02:31 UTC, orogenic commented on app.py
> +            record = db.session.query(Transaction).filter \
could also use vertical alignment with your explicit line continuation
```
record = db.session.query(Transaction) \
                   .filter(Transaction.id == request.form['transactionID']) \
                   .one()
```

2020-11-04 02:31 UTC, orogenic commented on static/transaction.js
> +    console.log('transID:' + transID);
extraneous console.log

2020-11-04 02:31 UTC, orogenic commented on static/transaction.js
> +    for (var td of tdTimestampElements) {
if you like saving lines, you don't need braces around oneline for, if, else, while statement bodies.
```
for ()
    ;
for ()
    ...

2020-11-04 02:31 UTC, orogenic commented on static/transaction.js
> +    if (!isReceipt) {
how about `if (!isReceipt && sliceIndex !== 0)`

2020-11-04 02:31 UTC, orogenic commented on static/transaction.js
> +    makeCellEditable(event, inputAttributes, timestampEdit);
can just inline stuff you don't need references to
```
makeCellEditable(event, {
    type: "datetime-local",
    name: "timestamp"
}, timestampEdit)
```

2020-11-05 00:56 UTC, orogenic requested changes
Tested. works. respond to the minor comments then do a squash and rebase or squash and merge to merge these commits.

2020-11-08 00:14 UTC, jonathan-mejia-deluna commented on app.py
> +            record = db.session.query(Transaction).filter \
That looks pretty neat. I was just thinking of trying to prevent lines from spilling over past column 80 which is some aesthetic rule I vaguely remember.

2020-11-08 00:22 UTC, jonathan-mejia-deluna commented on static/transaction.js
> +    for (var td of tdTimestampElements) {
This is a habit I picked up in an intro programming class. The code breaks if you were to add another line, so I consider having braces best practice.

2020-11-08 00:26 UTC, jonathan-mejia-deluna commented on static/transaction.js
> +    if (!isReceipt) {
I still want the block to run if sliceIndex is equal to 0 to handle the amountEdit case.

2020-11-08 00:34 UTC, jonathan-mejia-deluna commented on static/transaction.js
> +    makeCellEditable(event, inputAttributes, timestampEdit);
Also neat

2020-11-08 00:38 UTC, orogenic commented on static/transaction.js
> +    if (!isReceipt) {
find a way to restructure the conditional so you don't do slice when sliceIndex is 0. it will make the semantics clearer. keep in mind you can write conditionals such as `if (handler === amountEdit)`

2020-11-08 00:43 UTC, jonathan-mejia-deluna commented on static/transaction.js
> +    if (!isReceipt) {
I think that can only be accomplished if I were to add another conditional block. I wouldn't slice if the handler wasn't amount edit, and would slice if it was. Is that the kind of alternative you have in mind?

2020-11-08 00:45 UTC, orogenic commented on static/transaction.js
> +    if (!isReceipt) {
sounds like it might work, and then at that point you need not assign a default value of sliceIndex to 0 in the function signature because the only codepath that uses the value is the one where it's passed.

2020-11-08 00:48 UTC, orogenic commented on static/transaction.js
> +    if (!isReceipt) {
you can also reorder your code to use the conditional block you already have for isReceipt instead of having two separate ones, and then you also don't need to assign a default value to isReceipt in the function signature either because when not passed it is undefined which evaluates to false.

2020-11-08 01:11 UTC, jonathan-mejia-deluna commented on static/transaction.js
> +    if (!isReceipt) {
Actually nvm I got a better idea

2020-11-08 05:24 UTC, jonathan-mejia-deluna commented
Review when you can

2020-11-08 05:34 UTC, orogenic approved these changes

2020-11-11 18:14 UTC, orogenic commented
fyi you can merge this whenever you want. also fyi i deactivated the slack account cus the workspace is dead. dm me on discord for my other contact info if u like. there's not much point to keep developing an admin tool for a dead process so the weekly time requirement is officially over for now. feel free to keep doing whatever you want on this codebase. i may still use it to backport the existing data from google sheets and airtable.

2020-11-15 14:56 UTC, orogenic commented
i will merge this by tmmrw, unless you're still working on it

2020-11-15 23:23 UTC, merged

2020-11-17 15:41 UTC, orogenic commented on static/transaction.js
> +        var button = document.querySelector("td.receipt button");
this line doesn't make sense to me. it gets the first element in the document matching that query selector. how does this pertain to this specific row?

2020-11-17 16:41 UTC, jonathan-mejia-deluna commented on static/transaction.js
> +        var button = document.querySelector("td.receipt button");
I can probably fix this today